name: opa-example

releases:
- name: opa
  version: latest
- name: bpm
  sha1: 0cf53162bb246de6afb4c1eaf14becdb7865a217
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.8.0
  version: 0.8.0

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "3586.25"

instance_groups:
- name: opa
  instances: 1
  networks:
  - name: ((network_name))
  azs: [((zone))]
  jobs:
  - name: bpm
    release: bpm
  - name: opa
    release: opa
    properties:
      addr: "0.0.0.0:8181"
      authentication: "off"
      authorization: "off"
      format: "pretty"
      log-format: "json"
      log-level: "info"
      max-errors: 10
      server-diagnostics-buffer-size: 100
      tls:
        cert: ((tls_opa.certificate))
        private_key: ((tls_opa.private_key))
  stemcell: trusty
  vm_type: micro

variables:
- name: opa_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca

- name: tls_opa
  type: certificate
  options:
    ca: opa_ca
    common_name: ((opa_common_name))
    alternative_names: []

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 10000-30000
  update_watch_time: 10000-30000
